// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartDealerships.DataAccess.PSQL;

#nullable disable

namespace SmartDealerships.DataAccess.Migrations
{
    [DbContext(typeof(DealershipDbContext))]
    [Migration("20220609231209_FixedSomeModels3")]
    partial class FixedSomeModels3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderDetailsProduct", b =>
                {
                    b.Property<int>("OrdersId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductsId")
                        .HasColumnType("integer");

                    b.HasKey("OrdersId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("OrderDetailsProduct");
                });

            modelBuilder.Entity("SmartDealerships.DataAccess.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<int?>("ShoppingSessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingSessionId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("SmartDealerships.DataAccess.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Spare parts"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fuel filtes"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Battery"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Brake pads"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Brake rotor"
                        });
                });

            modelBuilder.Entity("SmartDealerships.DataAccess.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("LogoImage")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Truck shop"
                        });
                });

            modelBuilder.Entity("SmartDealerships.DataAccess.Models.OrderDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("SmartDealerships.DataAccess.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            CompanyId = 1,
                            Description = "Brakes squealing? Are you experiencing longer stopping distances? Get reliable, everyday performance for regular driving needs from Duralast brake pads, designed to meet your vehicles original equipment for form, fit, and function. Available only at AutoZone, Duralast brake pads use platform-specific, semi-metallic friction materials tailored to your vehicle. Replace rotors and hardware when replacing brake pads for better performance and less noise.",
                            Name = "Duralast Ceramic Brake Pads",
                            Price = 300.5m,
                            Sku = "MKD503"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 4,
                            CompanyId = 1,
                            Description = "Brakes squealing? Are you experiencing longer stopping distances? Get reliable, everyday performance for regular driving needs from Duralast brake pads, designed to meet your vehicles original equipment for form, fit, and function. Available only at AutoZone, Duralast brake pads use platform-specific, semi-metallic friction materials tailored to your vehicle. Replace rotors and hardware when replacing brake pads for better performance and less noise.",
                            Name = "Duralast Ceramic Brake Pads D924",
                            Price = 36.99m,
                            Sku = "D924"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            CompanyId = 1,
                            Description = "Brakes squealing? Are you experiencing longer stopping distances? Get reliable, everyday performance for regular driving needs from Duralast brake pads, designed to meet your vehicles original equipment for form, fit, and function. Available only at AutoZone, Duralast brake pads use platform-specific, semi-metallic friction materials tailored to your vehicle. Replace rotors and hardware when replacing brake pads for better performance and less noise.",
                            Name = "Duralast Ceramic Brake Pads D1339",
                            Price = 44.49m,
                            Sku = "D1339"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            CompanyId = 1,
                            Description = "Engineered to properly remove heat from the brake system,OE compliance for equal or better rotor performance, reduced pulsation, and noise.",
                            Name = "Duralast Brake Rotor 31069",
                            Price = 59.99m,
                            Sku = "31069"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CompanyId = 1,
                            Description = "Engineered to properly remove heat from the brake system,OE compliance for equal or better rotor performance, reduced pulsation, and noise.",
                            Name = "Duralast Brake Rotor 55097",
                            Price = 89.99m,
                            Sku = "55097"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            CompanyId = 1,
                            Description = "Engineered to properly remove heat from the brake system,OE compliance for equal or better rotor performance, reduced pulsation, and noise.",
                            Name = "Duralast Brake Rotor 55072DL",
                            Price = 79.99m,
                            Sku = "55072DL"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            CompanyId = 1,
                            Description = "Duralast® brand disc brake rotors are designed and engineered to match J431 and your vehicles original equipment performance. Our Duralast® rotors can replace your OE parts with no change in performance and safety. So when you need a part you can trust at a price you can afford.",
                            Name = "Duralast Brake Rotor 5333",
                            Price = 97.99m,
                            Sku = "55072DL"
                        });
                });

            modelBuilder.Entity("SmartDealerships.DataAccess.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "User"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("SmartDealerships.DataAccess.Models.ShoppingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ShoppingSessions");
                });

            modelBuilder.Entity("SmartDealerships.DataAccess.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int?>("ShoppingSessionId")
                        .HasColumnType("integer");

                    b.Property<string>("Telephone")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.HasIndex("ShoppingSessionId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kharkiv city, Buchmy 50",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2022, 6, 10, 2, 12, 8, 589, DateTimeKind.Utc).AddTicks(7411),
                            Email = "john.doe@gmail.com",
                            FirstName = "John",
                            LastName = "Doe",
                            ModifiedAt = new DateTime(2022, 6, 10, 2, 12, 8, 589, DateTimeKind.Utc).AddTicks(7462),
                            PasswordHash = "am9obmRvZTI0MTAK",
                            RoleId = 1,
                            Telephone = "380662016"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Pervomaiskiy",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2022, 6, 10, 2, 12, 8, 589, DateTimeKind.Utc).AddTicks(7473),
                            Email = "mykyta.kysil@nure.ua",
                            FirstName = "Mykyta",
                            LastName = "Kysil",
                            ModifiedAt = new DateTime(2022, 6, 10, 2, 12, 8, 589, DateTimeKind.Utc).AddTicks(7478),
                            PasswordHash = "MTIwOTE5OTM=",
                            RoleId = 2,
                            Telephone = "0662016521"
                        });
                });

            modelBuilder.Entity("OrderDetailsProduct", b =>
                {
                    b.HasOne("SmartDealerships.DataAccess.Models.OrderDetails", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartDealerships.DataAccess.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartDealerships.DataAccess.Models.CartItem", b =>
                {
                    b.HasOne("SmartDealerships.DataAccess.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("SmartDealerships.DataAccess.Models.ShoppingSession", "ShoppingSession")
                        .WithMany("CartItems")
                        .HasForeignKey("ShoppingSessionId");

                    b.Navigation("Product");

                    b.Navigation("ShoppingSession");
                });

            modelBuilder.Entity("SmartDealerships.DataAccess.Models.OrderDetails", b =>
                {
                    b.HasOne("SmartDealerships.DataAccess.Models.Company", "SellingCompany")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("SmartDealerships.DataAccess.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("SellingCompany");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartDealerships.DataAccess.Models.Product", b =>
                {
                    b.HasOne("SmartDealerships.DataAccess.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.HasOne("SmartDealerships.DataAccess.Models.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SmartDealerships.DataAccess.Models.User", b =>
                {
                    b.HasOne("SmartDealerships.DataAccess.Models.Company", "Company")
                        .WithMany("Owners")
                        .HasForeignKey("CompanyId");

                    b.HasOne("SmartDealerships.DataAccess.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartDealerships.DataAccess.Models.ShoppingSession", "ShoppingSession")
                        .WithOne("User")
                        .HasForeignKey("SmartDealerships.DataAccess.Models.User", "ShoppingSessionId");

                    b.Navigation("Company");

                    b.Navigation("Role");

                    b.Navigation("ShoppingSession");
                });

            modelBuilder.Entity("SmartDealerships.DataAccess.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SmartDealerships.DataAccess.Models.Company", b =>
                {
                    b.Navigation("Owners");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("SmartDealerships.DataAccess.Models.ShoppingSession", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
